version: "1.0"
info:
  model: int-scaffold
packages:
- name: IntranetAbsenceApiProject
  gitServerName: myGit
  gitUrl: https://github.com/cgodartSlagsoa
  gitUsername: cgodartSlagsoa
  gitBranch: main
